number1 = input("what is ur birthday?")
number2 = input("whats ur lucky number?")
number3 = input("whats ur door number?")
number4 = input("whats ur least favourite number?")
print(int(number1)+ int(number2)+ int(number3)+ int(number4))
